apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: amg-minicluster-aws-cpu
  namespace: default
spec:
  cleanup: false
  containers:
  - command: amg -problem 2 -n 120 120 120 -P 8 4 2
    environment:
      OMPI_MCA_btl_vader_single_copy_mechanism: cma
      OMP_NUM_THREADS: '1'
    image: ghcr.io/converged-computing/fractale-agent-experiments:amg2023
    launcher: false
  flux:
    arch: arm
    container:
      image: ghcr.io/converged-computing/flux-view-rocky:arm-9
  logging:
    quiet: true
  pod:
    nodeSelector:
      node.kubernetes.io/instance-type: m7g.16xlarge
  size: 1
  tasks: 64

