apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: efa-cluster
  region: us-east-1

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "ec2:DescribeImages"
        - "ec2:DescribeInstanceTypes"
        - "ec2:DescribeLaunchTemplateVersions"
        - "ec2:GetInstanceTypesFromInstanceRequirements"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        - "eks:DescribeNodegroup"        
        Resource: '*'

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]
managedNodeGroups:

  - name: ng-hpc7g-16xlarge
    availabilityZones: ["us-east-1a"]
    instanceType: hpc7g.16xlarge
    efaEnabled: true
    placement:
      groupName: performance-study
    volumeSize: 20
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 4
    iam:
      withAddonPolicies:
        autoScaler: true
    tags:
      nodegroup: ng-hpc7g-16xlarge
      kubernetes.io/cluster/efa-cluster: "owned"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/efa-cluster: "owned"
      k8s.io/cluster-autoscaler/node-template/label/nodegroup: ng-hpc7g-16xlarge
      Name: 'efa-cluster'
    propagateASGTags: true

  # This will be a node to install to - "sticky node"
  # Placement group is intentionally omitted for this general-purpose node.
  - name: ng-t3-medium
    instanceType: t3.2xlarge
    volumeSize: 20
    volumeType: gp2
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    iam:
      withAddonPolicies:
        autoScaler: true
    tags:
      nodegroup: ng-t3-medium
      kubernetes.io/cluster/efa-cluster: "owned"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/efa-cluster: "owned"
      k8s.io/cluster-autoscaler/node-template/label/nodegroup: ng-t3-medium
      Name: 'efa-cluster'
    propagateASGTags: true

   # ARM instance
  - name: ng-m7g-large
    instanceType: m7g.16xlarge
    efaEnabled: true
    placement:
      groupName: performance-study
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 4
    iam:
      withAddonPolicies:
        autoScaler: true
    tags:
      nodegroup: ng-m7g-large
      kubernetes.io/cluster/efa-cluster: "owned"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/efa-cluster: "owned"
      k8s.io/cluster-autoscaler/node-template/label/nodegroup: ng-m7g-large
      Name: 'efa-cluster'
    propagateASGTags: true

   # ARM instance
  - name: ng-c7g-large
    instanceType: c7g.16xlarge
    efaEnabled: true
    placement:
      groupName: performance-study
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 4
    iam:
      withAddonPolicies:
        autoScaler: true
    tags:
      nodegroup: ng-c7g-large
      kubernetes.io/cluster/efa-cluster: "owned"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/efa-cluster: "owned"
      k8s.io/cluster-autoscaler/node-template/label/nodegroup: ng-c7g-large
      Name: 'efa-cluster'
    propagateASGTags: true

  - name: ng-r7g-large
    instanceType: r7g.16xlarge
    efaEnabled: true
    placement:
      groupName: performance-study
    volumeSize: 30
    volumeType: gp2
    desiredCapacity: 0
    minSize: 0
    maxSize: 4
    iam:
      withAddonPolicies:
        autoScaler: true
    tags:
      nodegroup: ng-r7g-large
      kubernetes.io/cluster/efa-cluster: "owned"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/efa-cluster: "owned"
      k8s.io/cluster-autoscaler/node-template/label/nodegroup: ng-r7g-large
      Name: 'efa-cluster'
    propagateASGTags: true
